### ISSUE TITLE
No linux/arm64/v8 images available

### ISSUE THREAD

**Issue by chaicesan** [stackabletech/docker-images#330]
I am attempting to install and get an hbase cluster running using the helm charts. The operators install fine but when actually attempting to apply manifests to create the cluster objects (zookeepercluster, zookeepernode etc...) I am met with `Warning  Failed            4s (x2 over 18s)  kubelet            Failed to pull image "docker.stackable.tech/stackable/zookeeper:3.8.0-stackable23.1.0": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries`. Is this a known issue?

**Comment by Maleware** [comment]
Hey,
please be aware that multi arch images are in the organisation 'stackable-experimental'. We developed some groundwork and have up to a certain point images available. 

The newest available version of zookeeper image is `docker.stackable.tech/stackable-experimental/zookeeper:3.8.0-stackable0.42.0` This pulls you the ARM-version of Zookeeper. 

You can try it with docker pull docker.stackable.tech/stackable-experimental/zookeeper:3.8.0-stackable0.42.0

To have a closer look about which versions are available to you, you can look here: `https://repo.stackable.tech/#browse/browse:docker:v2%2Fstackable-experimental%2Fzookeeper%2Ftags%2F3.8.0-stackable0.42.0`

Greetings

**Comment by chaicesan** [comment]
Hello. Thanks for you reply. I will give this a go tomorrow too!

**Comment by chaicesan** [comment]
QQ are the helm charts located somewhere in github. I'd like to take a look at the templates to get an idea about what helm chart values are available.

**Comment by chaicesan** [comment]
Actually I think I may have found them. Although helm-experimental only contains the zookeeper-operator. Will using the standard helm charts work as long as I supply an arm image via the values file?

**Comment by Maleware** [comment]
What you actually wanna do is:
`helm install zookeeper-operator stackable-dev/zookeeper-operator --version=0.11.0-nightly --set image.repository=docker.stackable.tech/stackable-experimental/zookeeper-operator`

I assume you are in a docker-desktop or kind context, so this deploys you a zookeeper operator from the stackable nexus. You want to repeat the process for all operators you want to have, just check in the repo which one are available.

When you have installed your stack (I assume zookeeper, commons, secret and opa operator are a very good start) you want to deploy a product using kubectl. ( `kubectl apply -f example/.... .yaml` )

For this you want to have a yaml like in zookeeper-operator/example/ . You have to be careful here, because we have a breaking change in the yaml. Means you want to revert this ADR in your yaml https://docs.stackable.tech/home/nightly/concepts/product_image_selection.html

Of course you can build your own images using build_product_images.py and specify linux/arm64 as target platform and just take the one from your repo if tagged correctly. Same is true for the operators. You can compile them on your own, tag them and then just `helm install` with the corresponding tag

**Comment by chaicesan** [comment]
Thanks for the info. What do you mean when by 'ADR'?

**Comment by chaicesan** [comment]
Thanks for the help. I have successfully got a cluster up and running.
