### ISSUE TITLE
Apache SOLR

### ISSUE THREAD

**Issue by terrancesnyder** [stackabletech/docker-images#372]
Hello,

I've run many data platforms including a massive distributed platform in the past that used vagrant and headless puppet to manage aws, azure, and google cloud. The stack was very similar to this, however I do miss the inclusion of Apache SOLR into the data stack here.

Apache SOLR is a great addition to the overall data stack here as it fits nicely in the search and discovery side with integration with Hive, Spark, etc.

I am open to helping add SOLR to the stack here and spending some time. LMK if this works as a feature request and I can help shell out the process.

**Comment by Jimvin** [comment]
Hello Terrance, Search is a capability that we are looking to include in our stack though are leaning towards OpenSearch rather than Solr. This choice is partly because OpenSearch is a dependency for tools such as DataHub that we are also looking to onboard. If you're interested in working on OpenSearch we'd certainly appreciate your input.

**Comment by Jimvin** [comment]
A decision was made not to include Apache Solr in Stackable, so I will close this issue.
